.TH fifo 1  "Jan 1, 2014" "version 0.2.2" "USER COMMANDS"
.SH NAME
fifo \- Project FiFo console API client
.SH SYNOPSIS
.B fifo
[\-h|\-\-help] [\-V|\-\-version] [\-c|\-\-config config] [\-\-host host]
[\-u|\-\-user user] [\-P|\-\-password password] [\-v|\-\-verbose] [\-\-curl]
[\-\-api-version] {datasets, dtrace, roles, hypervisors, ipranges, networks,
orgs, packages, users, vms} <command>
.SH DESCRIPTION
This program allows to use the HTTP/REST API provided by Project FiFo from
the console and interact with it in a scripted manner.
.PP
Configuration data for the endpoint can either be passed via the command line
arguments or via the config file located (~/.fifo).
.SH OPTIONS
.TP
\-h|\-\-help
display a short help text, can be used for all sub commands
.TP
\-\-curl
Turn on print curl synopsis
.TP
\-V|\-\-version
shows the current version
.TP
\-v|\-\-verbose
Enables verbose debugging output
.TP
\-\-api-version
forces the API version, please use carefully.
.TP
\-c|\-\-config
select which section of the config file to use
.TP
\-\-host
manually selects the host to talk to, this is a fqdn or IP w/o the protocol
.TP
\-u|\-\-user
specifies the user to authorize with
.TP
\-P|\-\-password
specifies the password to authenticate with
.TP
\-p
as part of any
.B list
command the \-p option outputs the data in parsable format separating
the columns by a ':'
.TP
\-H
as part of any
.B list
command the \-H option will suppress the header to be printed making
parsing easier
.TP
\-\-fmt FMT
as part of any
.B list
command this defines the fields to be printed in order,
.B FMT
is a ',' separated list without whitespaces
.SH COMMANDS
.TP
fifo-datasets(1)
Commands to manage datasets.
.TP
fifo-dtrace(1)
Commands to manage D-Trace scripts.
.TP
fifo-groupings(1)
Commands to manage clusters and stacks.
.TP
fifo-hypervisors(1)
Commands to manage hypervisors.
.TP
fifo-ipranges(1)
Commands to manage IP-Ranges.
.TP
fifo-networks(1)
Commands to manage networks.
.TP
fifo-orgs(1)
Commands to manage organisations.
.TP
fifo-packages(1)
Commands to manage packages.
.TP
fifo-roles(1)
Commands to manage roles.
.TP
fifo-users(1)
Commands to manage users.
.TP
fifo-vms(1)
Commands to manage Zones and VMs.
.SH EXIT STATUS
fifo returns zero on a successful execution and one when a error
occurred printing some details of the error.
.SH AUTHOR
Heinz N. 'Licenser' Gies (heinz (at) licenser.net)
.SH SEE ALSO
fifo-vms(1), fifo-groupings(1), fifo-users(1)
